import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generatePDF = async (title, content) => {
    return new Promise((resolve, reject) => {
        try {
            const filename = `${uuidv4()}.pdf`;
            const pdfDir = path.join(__dirname, '..', 'generated_pdfs');

            if (!fs.existsSync(pdfDir)) {
                fs.mkdirSync(pdfDir, { recursive: true });
            }

            const filepath = path.join(pdfDir, filename);
            const doc = new PDFDocument({ margin: 50 });
            const writeStream = fs.createWriteStream(filepath);

            doc.pipe(writeStream);

            // Header with gradient effect
            doc.rect(0, 0, doc.page.width, 100)
                .fill('#1a1a2e');

            doc.fontSize(28)
                .fillColor('#8b5cf6')
                .text(title, 50, 40);

            // Content
            doc.moveDown(2);
            doc.fontSize(12)
                .fillColor('#333333');

            // Parse content and format
            const lines = content.split('\n');
            let y = 120;

            lines.forEach(line => {
                if (line.startsWith('# ')) {
                    doc.fontSize(20)
                        .fillColor('#1a1a2e')
                        .text(line.substring(2), 50, y);
                    y += 30;
                } else if (line.startsWith('## ')) {
                    doc.fontSize(16)
                        .fillColor('#4a4a6a')
                        .text(line.substring(3), 50, y);
                    y += 25;
                } else if (line.startsWith('- ')) {
                    doc.fontSize(12)
                        .fillColor('#333333')
                        .text('• ' + line.substring(2), 60, y);
                    y += 18;
                } else if (line.trim()) {
                    doc.fontSize(12)
                        .fillColor('#333333')
                        .text(line, 50, y, { width: doc.page.width - 100 });
                    y += doc.heightOfString(line, { width: doc.page.width - 100 }) + 5;
                } else {
                    y += 10;
                }

                // Add new page if needed
                if (y > doc.page.height - 80) {
                    doc.addPage();
                    y = 50;
                }
            });

            // Footer
            doc.fontSize(10)
                .fillColor('#999999')
                .text('Generated by Nexus AI', 50, doc.page.height - 50, { align: 'center' });

            doc.end();

            writeStream.on('finish', () => {
                resolve({
                    filename,
                    path: `/pdfs/${filename}`
                });
            });

            writeStream.on('error', reject);

        } catch (error) {
            reject(error);
        }
    });
};
