# ai-layout-project/backend/pdf_generator.py

import sys
import json
from fpdf import FPDF
from io import BytesIO

# --- Your PDF Generation Logic (from previous response, adjusted for direct output) ---
def create_multiplication_tables_pdf_bytes(tables_data, title="Multiplication Tables"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 15, title, align='C', ln=True)
    pdf.ln(10)

    header_font_size = 14
    content_font_size = 11
    header_color = (0, 102, 204)
    content_color = (51, 51, 51)
    line_height = 7

    current_x = pdf.get_x()
    start_y = pdf.get_y()
    column_width = 60
    column_spacing = 10
    tables_per_row = 3

    table_count = 0
    for table_num, lines in tables_data.items():
        if pdf.get_y() > (pdf.h - 30) and table_count % tables_per_row == 0:
            pdf.add_page()
            current_x = pdf.l_margin
            pdf.set_y(pdf.t_margin + 10)
            start_y = pdf.get_y()

        if table_count % tables_per_row == 0:
            pdf.set_y(start_y)
            current_x = pdf.l_margin
        else:
            current_x += column_width + column_spacing

        pdf.set_xy(current_x, pdf.get_y())

        pdf.set_font("Arial", "B", header_font_size)
        pdf.set_text_color(*header_color)
        pdf.cell(column_width, 10, f"Table of {table_num}", align='C', ln=True)
        pdf.set_x(current_x)

        pdf.set_font("Arial", "", content_font_size)
        pdf.set_text_color(*content_color)
        for line in lines:
            pdf.set_x(current_x)
            pdf.cell(column_width, line_height, line, align='L', ln=True)

        pdf.ln(2)

        table_count += 1

        if table_count % tables_per_row == 0:
            start_y = pdf.get_y()

    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, f"Generated by AI (Multiplication Tables) - Page {pdf.page_no()}/{{nb}}", align='C')

    # Return PDF as bytes
    return pdf.output(dest='S').encode('latin-1')

def generate_multiplication_tables_data(start_table, end_table, max_multiplier=10):
    tables_data = {}
    for i in range(start_table, end_table + 1):
        current_table_lines = []
        for j in range(1, max_multiplier + 1):
            current_table_lines.append(f"{i} x {j} = {i * j}")
        tables_data[i] = current_table_lines
    return tables_data
# --- END PDF Generation Logic ---

if __name__ == '__main__':
    # This part handles command-line arguments and outputs PDF to stdout
    if len(sys.argv) != 3:
        # If not enough arguments, print an error to stderr and exit
        print("Usage: python pdf_generator.py <start_table> <end_table>", file=sys.stderr)
        sys.exit(1)

    try:
        start_table = int(sys.argv[1])
        end_table = int(sys.argv[2])

        if start_table > end_table or start_table < 1 or end_table > 100:
            print("Error: Invalid table range. Start must be <= End, and within 1-100.", file=sys.stderr)
            sys.exit(1)

        tables_data = generate_multiplication_tables_data(start_table, end_table)
        pdf_bytes = create_multiplication_tables_pdf_bytes(
            tables_data,
            title=f"Multiplication Tables {start_table} to {end_table}"
        )
        
        # Write the PDF bytes directly to stdout
        sys.stdout.buffer.write(pdf_bytes)
        sys.stdout.flush() # Ensure all output is sent
        sys.exit(0) # Exit successfully

    except ValueError:
        print("Error: Table numbers must be integers.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        sys.exit(1)